name: interstellar-armada # you probably want to 'snapcraft register <name>'
version: '0.4.0-dev' # just for humans, typically '1.2+git' or '1.3.2'
summary: A 3D space combat action/sim game for midcore players. In development. # 79 char long summary

description: |
  Interstellar Armada: Galactic Ace is a mission-based 3D space combat simulator where
  you take the role of a mercenary fighter pilot. Complete missions to earn fortune and 
  fame and help the rising Empire unite humankind under its flag, or aid the shrinking
  number of opposing Republic worlds to stop its advance.

  The game uses Newtonian mechanics with an assisted, six degrees of freedom flight model 
  and supports keyboard, mouse and joystick controls.

  This early development version features several training and combat missions with basic
  destroy/protect scenarios. 

  The game is built with open web technologies and is packaged as a standalone app
  using Electron.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

icon: setup/gui/icon-ace.png

apps:
  interstellar-armada:
    command: wrapper
    plugs: [unity7, opengl, network]

parts:
  interstellar-armada:
    plugin: dump
    stage-packages:
      - libnss3
      - fontconfig-config
      - gnome-themes-standard
    source: source/
    organize:
      wrapper: usr/bin/wrapper
      libnode.so: usr/lib/x86_64-linux-gnu/libnode.so
      libffmpeg.so: usr/lib/x86_64-linux-gnu/libffmpeg.so
